/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package org.crashstar.scala

import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner
import org.slf4j.{Logger, LoggerFactory}

class LibrarySuite extends FunSuite {

  val log : Logger = LoggerFactory.getLogger(classOf[LibrarySuite])

  log.info("#################### BEGIN TEST: LibrarySuite ####################")

  test("someLibraryMethod is always true") {
    log.debug("First logging with logback")
    def library = new Library()
    log.debug("End first logging with logback")
    assert(library.someLibraryMethod)
  }

  test("someLibraryMethod2 is always true") {
    log.debug("Second logging with logback")
    def library = new Library()
    log.debug("End second logging with logback")
    assert(true)
  }

  test("someLibraryMethod3 is always true") {
    log.debug("One more logging with logback")
    def library = new Library()
    log.debug("End one more logging with logback")
    assert(true)
  }
}
